### ISSUE TITLE
OpenTracing support 

### ISSUE THREAD

**Issue by loganvolkers** [chonton/apm-client#1]
http://opentracing.io/ -- Need I say more?

**Comment by chonton** [comment]
Pull request welcome.

**Comment by tylerbenson** [comment]
Stay tuned...

**Comment by tylerbenson** [comment]
Sorry... I forgot to circle back on this.

We have official OpenTracing support here: https://docs.datadoghq.com/tracing/setup/java/#opentracing-api

**Comment by loganvolkers** [comment]
Thanks @tylerbenson!
